Data pipeline
DalbergDataInsights/icohs-analysis pull request #6
Opened 2020-08-11 14:46 UTC by nlubalo

Review the new updated db_script.py.

2020-08-13 09:37 UTC, dsementsov requested changes

2020-08-13 09:37 UTC, dsementsov commented on src/clean_and_process.py
> +ENGINE_rename = engine.get_engine()
You don't need that variable

2020-08-13 09:37 UTC, dsementsov commented on src/clean_and_process.py
> +
This is a duplication of the get_engine file

2020-08-13 09:37 UTC, dsementsov commented on src/clean_and_process.py
> +###########################
Can we have this file at the root of repo and rename it to app.py?

2020-08-13 09:37 UTC, dsementsov commented on src/db_insert.py
> +        return ENGINE
This is a duplicate of the get_engine file

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +
this is a duplicate of the get_engine

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +    print(statement, str(datetime.datetime.now() - startTime))
This method is duplicated. Move it to separate helpers.py file and import when needed.

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +VAR_CORR_PATH = ENGINE['var_correspondance_data']
this variable is not needed. Just read from the key

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +
Constants should be at the top of the file

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +    data = pd.read_csv(path, usecols=USECOLS, dtype=DTYPES)
you can also set the index to be Unnamed: 0 right away

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +        y = date.split("W")[0]
y, w = (date.split('W'))

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +
Allocate data resources only when you need them!

If you want this to be less RAM efficient, I would even read-write the data in chunks.

You are doing:

read data 1 
read data 2 
read data 3

process data 1
process data 2 
process data 3

You need to be doing:

read data 1
process data 1
return data 1 or write data 1

read data 2 
process data 2
...

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +
This is highly redundant and creates an overhead!

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +                             new_dhis_report_df])
I am not sure we need reporting and data in the same df though

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +    new_ids = set(new_dhis_report_df['orgUnit'].unique())
set and unique() does the same thing

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +    list_ids = list(new_ids.intersection(old_ids))
now what you could do is just 

set(old_dhis_report_df['orgUnit'].tolist() + new_dhis_report_df['orgUnit'].tolist())

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/clean.py
> +    list_ids = list(new_ids.intersection(old_ids))
you also could have filtered the dfs before concatting them together

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/process.py
> +ENGINE_rename = engine.get_engine()
unused variable

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/process.py
> +
duplication of get_engine

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/process.py
> +    print(statement, str(datetime.datetime.now() - startTime))
duplicate method

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/process.py
> +VAR_CORR_PATH = ENGINE['var_correspondance_data']
unnecessary declaration

2020-08-13 09:37 UTC, dsementsov commented on src/pipeline_func/process.py
> +    data_df_report = data[data['dataElement'].isin(report_indics)].copy()
you allocate memory 20 lines before you use it.

2020-12-11 10:54 UTC, closed without merging

2020-12-11 10:54 UTC, nbigaud commented
Outdated I think